version: '2' 
services:
  web:
    image: nginx:latest
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ../:/code/
    links:
        - php
    ports:
      - ${WEB_PORT}:80
        
  php:
    image: tanasecosminromeo/pdfmaker
    build: .
    env_file:
      - ../.env
    volumes:
      - ../:/code/